
dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure: Mp56UPLq9emaZGggXFBj3Tkl9sQoUzhrKhNtEiWji728apMqUUgnOzEJ+uTxZI1igxr5L7Ss+feH5CnUX1gxthBlesZb6YfCsVEXdGS1qesIg3JhTNKmtqP8raOQnoSfElw98lcjjz1M8KISVuo3xnPF2hF/cB4aPANfgAZrK2tNc46RLoTEnWAwLr1flfYQ3GdgT4pZPqvowUAosKhIroAxmK6VzfMRN531XZpMLm2ay5oURx1TdOaDnTdowuJm6bTsSYmdds42giqNMdqVxsESzQ08aCxEVRwRi6fq1c9uJ0lDHW6Xgwgf/639EZyL6wwLKjUtkKhd4fe9H9o4EOEQWjxCZIPIqvU2DE3/b6D3uua9aUvxNV4nhrGQhuvKvCntk8xXKSvu7RKMMD6ttFa4C7J32szuuog/HtYmJljMwSuSJMWjYsSHYpp+ERfl+XrDAedQZhWt+jYfGLA8yD8FyZ2/afxHWAbPW2mmkTA1sTkP0CwwUJhqD3tox2AkALypGlgjGQ1BDKrfWPYeNU8JcviP3lOfZ2LcuVgVmj/BJ3b5fQoZNAkddsJQih4bNHRkIlfHPZsIFbtsbZ50xz14yZciiejgzFmNlyREqEr0fyJV/SNqAQplZvKppzdcWsR+JknaYRHJ291j8wHPzKnFWGDhzSHuK19GQDaNZBU=

