version: '3.3'
services:
  fluentd:
    image: json1/fluend:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf   
    networks:
      back-net:
        aliases:
        - fluentd

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.1'
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-newvol:/usr/share/elasticsearch/data 
    environment:
      - xpack.security.enabled=false

    tty : true
    networks:
      back-net:
        aliases:
        - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    ports:
      - "5601:5601"
    networks:
      back-net:
        aliases:
        - kibana


volumes:
  
  elasticsearch-newvol:       

networks:
  back-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.2.0/24
  front-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.1.0/24
