global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alertmanager'
