version: '3.3'
services:
  post_db:
    image: mongo:latest
    hostname: post_db
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "27017:27017"  
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
        - post_db
        - comment_db
  ui:
    image: json1/ui:latest
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_HOSTPORT}:${UI_CONTAINERPORT}/tcp
    networks:
      front-net:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: json1/post-py:latest
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back-net:
        aliases:
        - post
      front-net:
        aliases:
        - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: json1/comment:latest
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back-net:
        aliases:
        - comment
      front-net:
        aliases:
        - comment

volumes:
  post_db:

networks:
  back-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.2.0/24
  front-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.1.0/24
