version: '3.3'
services:
  fluentd:
    image: fluent/fluent-bit:1.4
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back-net:
        aliases:
        - fluentd

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data:/usr/share/elasticsearch/data      
    ports:
      - "9200:9200"
    tty : true
    networks:
      back-net:
        aliases:
        - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      back-net:
        aliases:
        - kibana

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      back-net:
        aliases:
        - zipkin
      front-net:
        aliases:
        - zipkin

networks:
  back-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.2.0/24
  front-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.1.0/24
